### ISSUE TITLE
Bug color doesn't change to green in FF 89.0

### ISSUE THREAD

**Issue by jamiolee** [BrianGilbert/xdebug-helper-for-firefox#29]
When debugging is enabled the icon in the address bar no longer turns green, it just stays a gray color. It was working perfectly for me on FF version 88.

**Comment by aaronELBorg** [comment]
Me too.  FF 89.0 (64-bit) on MacOS

**Comment by juandlr** [comment]
It's only happening in firefox's dark theme.

**Comment by Roy-Orbison** [comment]
@BrianGilbert Mozilla has basically acknowledged that his is a hack to ensure visibility of icons. The relevant CSS:
```css
/* URL bar and page action buttons */

/* The background can be very dark and if the add-on uses a black-ish svg it
   will be barely visible. In the future we should have a standardized SVG
   solution we can apply to add-on icons, for now we can only try to make them
   visible through some filtering tricks */
:root[lwt-toolbar-field-brighttext] #urlbar:not([focused="true"]) .urlbar-addon-page-action[style*=".svg"] > .urlbar-icon,
:root[lwt-toolbar-field-focus-brighttext] #urlbar[focused="true"] .urlbar-addon-page-action[style*=".svg"] > .urlbar-icon {
  filter: grayscale(100%) brightness(20%) invert();
}

@media (prefers-color-scheme: dark) {
  /* As above, but for the default theme in dark mode, which suffers from the same issue */
  :root:not(:-moz-lwtheme) .urlbar-addon-page-action[style*=".svg"] > .urlbar-icon {
    filter: grayscale(100%) brightness(20%) invert();
  }
}
```
Even if they do make it possible to specify dark-mode icons, so the colour is restored, it really would be best not to rely on colour at all, and change the icon itself. It would resolve this issue as well as improve accessibility. Something that indicates the debugging process, such as something to symbolise looking (magnifying glass, binoculars, etc.), or the current line being analysed (something like [this](https://www.flaticon.com/free-icon/file_2521853)), or maybe mnemonic (e.g. steps for "stepping" through the code).

**Comment by Roy-Orbison** [comment]
Also you can work around this issue for now by using FF's [built-in `userChrome.css` feature](https://www.userchrome.org/), and adding the following rule:
```css
#pageAction-urlbar-_806cbba4-1bd3-4916-9ddc-e719e9ca0cbf_ .urlbar-icon {
	filter: none !important;
}
```
